name: Check Markdown
# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]
permissions: read-all
jobs:
  # This workflow contains a single job called "lint"
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
